on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: npm install and build
        run: |
          npm ci
          npm run build
      - name: Deploy
        uses: actions/upload-pages-artifact@v1
        with:
          path: "dist/"
